ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

SELECT * FROM DBA_USERS;
SELECT * FROM DBA_TABLESPACES;
SELECT * FROM DBA_DATA_FILES;

CREATE TABLESPACE ITM2019
DATAFILE 'ITM.DBF'
SIZE 50M


CREATE USER RONALD2019
IDENTIFIED BY ronald2019
DEFAULT TABLESPACE ITM2019
QUOTA UNLIMITED ON ITM2019;

GRANT DBA TO ADMINISTRADOR
GRANT CREATE TABLE TO RONALD2019 WITH ADMIN OPTION
    
CREATE PROFILE ADMINISTRADOR LIMIT
    PASSWORD_LIFE_TIME 100
    SESSIONS_PER_USER 2
    IDLE_TIME 30
    FAILED_LOGIN_ATTEMPTS UNLIMITED;        
    
    ALTER USER RONALD2019
    PROFILE ADMINISTRADOR;


CREATE TABLE USUARIOS (
  ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  CEDULA NUMERIC NOT NULL,
  NOMBRE VARCHAR(300),
  FECHA_NACIMIENTO TIMESTAMP NOT NULL,
  TIPO_DOCUMENTO VARCHAR(255)
  )

TABLESPACE ITM2019

CREATE TABLE DOCUMENTOS(
ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
ID_DOCUMENTO NUMERIC,
 FOREIGN KEY (ID_DOCUMENTO) REFERENCES USUARIOS(ID))
 
 TABLESPACE ITM2019
 
 SELECT * FROM USUARIOS

